- name: Download vscode package
  get_url:
    url: "{{ vscode_url }}"
    dest: "{{ vscode_file }}"

- name: Add vscode package
  shell: dpkg -i "{{ vscode_file }}"
  become: True

- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install editor packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: True

- name: Cleanup
  file:
    path: "{{ vscode_file }}"
    state: absent

- name: Install vscode extensions
  shell: code --install-extension "{{ item }}"
  with_items: "{{ vscode_extensions }}"
  when: vscode_enable_extensions