- name: Install ppas
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items: "{{ ppas }}"
  become: True

- name: Remove unnecessary ppas
  apt_repository:
    repo: "{{ item }}"
    state: "absent"
    codename: "sylvia"
  with_items: "{{ ppas }}"
  become: True

- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install video packages
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages }}"
  become: True

#- name: Install scripts
#  file: 
#    src="{{ role_path }}/files/{{ item }}"
#    dest="/usr/local/bin/{{ item }}"
#    state=link
#  with_items: "{{ scripts }}"
#  become: True
