- name: Ensure ppas are installed
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    codename: "xenial"
  with_items: "{{ ppas }}"
  become: True

- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install fun packages
  package: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ packages }}"
  become: True

- name: Activate toilet
  lineinfile:
    dest: "~/.bashrc"
    regexp: ".*toilet.*"
    line: "toilet --metal '\_Sergiu_/'"
  become: false

- name: Activate fortune
  lineinfile:
    dest: "~/.bashrc"
    regexp: ".*fortune.*"
    line: "fortune"
  become: false
