- name: Add spotify respository
  apt_repository: "deb http://repository.spotify.com stable non-free"
    
- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install audio packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: True
