- name: Add Apt Keys
   apt_key: id=BBEBDCB318AD50EC6865090613B00F1FD2C19886 keyserver="hkp://keyserver.ubuntu.com:80" state=present


- name: Add respository
  apt_repository: repo="deb http://repository.spotify.com stable non-free"
    
- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install audio packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: True
