- name: Spotify package list
  copy:
    content: "deb http://repository.spotify.com stable non-free"
    dest: /etc/apt/sources.list.d/spotify.list
    force: no
    group: sys
    owner: root
    mode: 0644
  become: True

- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install audio packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: True

