- name: Install util packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: True

- name: Activate undistract-me
  lineinfile:
    dest: "~/.bashrc"
    regexp: ".*undistract-me\\.sh.*"
    line: "source /etc/profile.d/undistract-me.sh"
  become: false

- name: Alias ls -lhA
  lineinfile:
    dest: "~/.bashrc"
    regexp: ".*ll=.*"
    line: "alias ll='ls -lhA'"
  become: false
