
#- name: add VirtualBox repo signing key
#  apt_key: 
#    state: absent
#    url: http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
#  become: True

- name: Download Virtualbox deb file.
  get_url:
    url: "{{ url }}"
    dest: "{{ file }}"

- name: Add Virtualbox package.
  shell: dpkg -i "{{ file }}"
  become: True

- name: Update cache
  apt:
    update_cache: True
  become: True

- name: Install Virtualbox package.
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages }}"
  become: true
  