- name: Download pub key to add in apt for Virtualbox
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ url_keys }}"
  become: true

- name: Check if file virtualbox.list exists or not
  stat: 
    path: "{{ virtualbox_apt_file }}"
  register: status
  become: true

- name: Add virtualbox.list to apt
  file:
    path: "{{ virtualbox_apt_file }}"
    state: touch
  when: status.stat.exists == false
  become: true

- name: Add line with repo in virtualbox.list
  lineinfile:
    path: "{{ virtualbox_apt_file }}"
    regexp: '^deb [arch=amd64] https://download.virtualbox'
    line: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ distrib }} contrib"
  become: true

- name: Update cache apt
  apt:
    update_cache: True
  become: True

- name: Install apt virtualbox packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: True
